### ISSUE TITLE
Weak material of casing

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#28]
**Describe the bug**
 The material has a high tendency to break. It is quite fragile

![image](https://user-images.githubusercontent.com/66819699/98521119-522a0100-2273-11eb-9873-f1650775924d.png)

![image](https://user-images.githubusercontent.com/66819699/98521142-5a823c00-2273-11eb-9da1-8dec0848b355.png)

![image](https://user-images.githubusercontent.com/66819699/98521527-d7151a80-2273-11eb-9c08-062c22bfca2e.png)

![image](https://user-images.githubusercontent.com/66819699/98521600-f01dcb80-2273-11eb-9967-512fc75d558b.png)

**Comment by xmirob** [comment]
It is designed in the case of wearables to press the part in the hole to open the cover safely. Anyway, hole click system will be changed to the system as it is in AP Nurse Home Base. Printed arrow will show where to open the cover. Holes for screws will be removed in version 4 completely. Only holder will be used for fixation to the wall. The thin layer on the wearables for diodes will be thicker and will be fixed by separators.

**Comment by EERCrso** [comment]
cele by to chcelo spravit hrubšie už sa mi to cele rozlamalo skoro

**Comment by xmirob** [comment]
Walls, bottom and top side are 0,2 mm thicker in V4 Base model. Screw holes in Base V4 model are removed.

**Comment by xosuskyf** [comment]
The V3 version of casing is much harder with standard string material. Also in the case of string material, the screw holes in the sensor board casing are better for stabilisation of the PCB board in the casing.

**Comment by EERCrso** [comment]
hey to SLA je krehke jak fras 
![image](https://user-images.githubusercontent.com/66819699/99235637-641d1e00-27f6-11eb-8524-2a6887fefe91.png)

**Comment by EERCrso** [comment]
problem vyriešeni odsttranenim SLA tlače
